# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.3
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
<<<<<<< HEAD
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/NpageLibrary.xcworkspace -scheme NpageLibrary-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
=======
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/NpageLibary.xcworkspace -scheme NpageLibary-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
>>>>>>> b6b987f7bbd7525068a49c41f8ee92ca6e7f8ed9
- pod lib lint
